// Quick-and-simple test provider — returns an instant, canned response so the
// SSE/signal-patching pipeline can be verified end-to-end without waiting on
// (or paying for) a real Anthropic call. Enable with AI_PROVIDER=mock in .env.
export async function* generate({ condition }) {
  await new Promise(resolve => setTimeout(resolve, 400));

  const json = {
    title: 'Mock Item — Sample Product for Testing',
    description:
      'This is a mock description generated by the test provider, standing in for the real AI output.\n\n' +
      'It covers what the item is and its key features, just like a real listing would.\n\n' +
      'Condition: this mock item shows minimal signs of wear and is fully functional, with all included parts and accessories accounted for.',
    item_specifics: { Brand: 'MockBrand', Color: 'Blue', Material: 'Plastic' },
    category_id: '12345',
    category_name: 'Test Category (Mock)',
    category_suggestions: [
      { id: '22222', name: 'Alt Category A (Mock)' },
      { id: '33333', name: 'Alt Category B (Mock)' },
    ],
    condition: condition || 'USED_GOOD',
    suggested_price: 19.99,
  };

  yield { field: 'ai_raw_output', value: JSON.stringify(json, null, 2) };

  const fields = [
    'title', 'description', 'item_specifics', 'category_id', 'category_name',
    'category_suggestions', 'condition', 'suggested_price',
  ];
  for (const field of fields) {
    yield { field, value: json[field] };
  }
}
